"""Render a Fiberarticle document to an Overleaf-ready LaTeX project zip.

main.tex uses the journal template's document class; [n] citation markers
become \\cite{key} calls resolved against refs.bib (generated from the run's
papers); figure/table placeholders become commented TODO stubs the author
fills in. The zip compiles on Overleaf as-is.
"""

import io
import re
import zipfile

from export.citations import _bibtex_key, to_bibtex
from latex.templates import LatexTemplate, template_for, vendored_files

_CITE_RE = re.compile(r"\[(\d+(?:\s*,\s*\d+)*)\]")
_PLACEHOLDER_RE = re.compile(r"^\[(.*placeholder.*)\]$", re.IGNORECASE)

# Order matters: backslash first.
_ESCAPES = [
    ("\\", r"\textbackslash{}"),
    ("&", r"\&"),
    ("%", r"\%"),
    ("$", r"\$"),
    ("#", r"\#"),
    ("_", r"\_"),
    ("{", r"\{"),
    ("}", r"\}"),
    ("~", r"\textasciitilde{}"),
    ("^", r"\textasciicircum{}"),
]


def escape_latex(text: str) -> str:
    for char, replacement in _ESCAPES:
        text = text.replace(char, replacement)
    return text


def _bib_keys(papers: list[dict]) -> list[str]:
    """Keys in paper order, deduplicated the same way to_bibtex does."""
    keys: list[str] = []
    seen: set[str] = set()
    for paper in papers:
        key = _bibtex_key(paper)
        while key in seen:
            key += "x"
        seen.add(key)
        keys.append(key)
    return keys


def _convert_body(content: str, keys: list[str]) -> str:
    """Escape prose and turn [n] markers into \\cite{...} calls."""
    paragraphs: list[str] = []
    for raw in content.split("\n"):
        line = raw.strip()
        if not line:
            continue
        placeholder = _PLACEHOLDER_RE.match(line)
        if placeholder:
            inner = escape_latex(placeholder.group(1))
            paragraphs.append(
                "% TODO: " + inner + "\n"
                "\\begin{figure}[htbp]\n"
                "  \\centering\n"
                "  % \\includegraphics[width=\\linewidth]{placeholder}\n"
                f"  \\caption{{{inner}}}\n"
                "\\end{figure}"
            )
            continue
        # Protect citation markers from escaping, then restore as \cite.
        tokens: dict[str, str] = {}

        def stash(match: re.Match) -> str:
            numbers = [int(n) for n in match.group(1).replace(" ", "").split(",")]
            valid = [keys[n - 1] for n in numbers if 1 <= n <= len(keys)]
            if not valid:
                return match.group(0)
            token = f"@@CITE{len(tokens)}@@"
            tokens[token] = "\\cite{" + ",".join(valid) + "}"
            return token

        line = _CITE_RE.sub(stash, line)
        line = escape_latex(line)
        for token, cite in tokens.items():
            line = line.replace(token, cite)
        paragraphs.append(line)
    return "\n\n".join(paragraphs)


def render_main_tex(document: dict, papers: list[dict]) -> str:
    template: LatexTemplate = template_for(document.get("template") or "generic")
    keys = _bib_keys(papers)
    title = escape_latex(document.get("title") or "Untitled")
    authors = document.get("authors") or []
    author_text = (
        " \\and ".join(escape_latex(a) for a in authors)
        if authors
        else "Author Name"
    )

    lines: list[str] = [
        "% Generated by Fiberarticle. Compiles on Overleaf as-is.",
        template.documentclass,
    ]
    if template.preamble:
        lines.append(template.preamble.rstrip())
    lines.extend(
        [
            "\\usepackage[utf8]{inputenc}",
            "\\usepackage{graphicx}",
            "",
            f"\\title{{{title}}}",
            template.author_command.format(authors=author_text),
            "",
            "\\begin{document}",
            "\\maketitle",
            "",
        ]
    )

    for section in document.get("sections") or []:
        heading = (section.get("heading") or "Section").strip()
        content = section.get("content") or ""
        if heading.lower() == "abstract":
            lines.append("\\begin{abstract}")
            lines.append(_convert_body(content, keys))
            lines.append("\\end{abstract}")
        else:
            lines.append(f"\\section{{{escape_latex(heading)}}}")
            lines.append(_convert_body(content, keys))
        lines.append("")

    lines.extend(
        [
            f"\\bibliographystyle{{{template.bib_style}}}",
            "\\bibliography{refs}",
            "",
            "\\end{document}",
            "",
        ]
    )
    return "\n".join(lines)


def render_project_zip(document: dict, papers: list[dict]) -> bytes:
    template = template_for(document.get("template") or "generic")
    main_tex = render_main_tex(document, papers)
    refs_bib = to_bibtex(papers) if papers else "% no references\n"

    readme = (
        "Fiberarticle LaTeX export\n"
        "=========================\n\n"
        f"Template: {template.label}\n\n"
        "To compile: upload this zip to Overleaf (New Project > Upload Project)\n"
        "or run pdflatex + bibtex locally.\n\n"
        "Files:\n"
        "  main.tex  - the manuscript\n"
        "  refs.bib  - references generated from your run's papers\n"
    )
    if template.vendored:
        readme += "".join(
            f"  {name}  - journal class/style, included\n" for name in template.vendored
        )
    if template.note:
        readme += f"\nNote: {template.note}\n"
    readme += (
        "\nFigure and table placeholders are marked with % TODO comments.\n"
        "Search main.tex for TODO to fill them in.\n"
    )

    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("main.tex", main_tex)
        archive.writestr("refs.bib", refs_bib)
        archive.writestr("README.txt", readme)
        for name, data in vendored_files(template):
            archive.writestr(name, data)
    return buffer.getvalue()
